{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "registry-rewriter.fullname" . }}
  labels:
    app: {{ template "registry-rewriter.name" . }}
    chart: {{ template "registry-rewriter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "registry-rewriter.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: {{ template "registry-rewriter.fullname" . }}
{{- end -}}
