{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: {{ .Values.serviceAccount.name }}
  labels:
    app: {{ template "registry-rewriter.name" . }}
    chart: {{ template "registry-rewriter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
